# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nowcoder/my_item

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nowcoder/my_item

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nowcoder/my_item/CMakeFiles /home/nowcoder/my_item/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nowcoder/my_item/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hook_test

# Build rule for target.
hook_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hook_test
.PHONY : hook_test

# fast build rule for target.
hook_test/fast:
	$(MAKE) -f CMakeFiles/hook_test.dir/build.make CMakeFiles/hook_test.dir/build
.PHONY : hook_test/fast

#=============================================================================
# Target rules for targets named myitem

# Build rule for target.
myitem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myitem
.PHONY : myitem

# fast build rule for target.
myitem/fast:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/build
.PHONY : myitem/fast

#=============================================================================
# Target rules for targets named mytest

# Build rule for target.
mytest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mytest
.PHONY : mytest

# fast build rule for target.
mytest/fast:
	$(MAKE) -f CMakeFiles/mytest.dir/build.make CMakeFiles/mytest.dir/build
.PHONY : mytest/fast

SourceCodes/fd_manager.o: SourceCodes/fd_manager.cc.o

.PHONY : SourceCodes/fd_manager.o

# target to build an object file
SourceCodes/fd_manager.cc.o:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/SourceCodes/fd_manager.cc.o
.PHONY : SourceCodes/fd_manager.cc.o

SourceCodes/fd_manager.i: SourceCodes/fd_manager.cc.i

.PHONY : SourceCodes/fd_manager.i

# target to preprocess a source file
SourceCodes/fd_manager.cc.i:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/SourceCodes/fd_manager.cc.i
.PHONY : SourceCodes/fd_manager.cc.i

SourceCodes/fd_manager.s: SourceCodes/fd_manager.cc.s

.PHONY : SourceCodes/fd_manager.s

# target to generate assembly for a file
SourceCodes/fd_manager.cc.s:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/SourceCodes/fd_manager.cc.s
.PHONY : SourceCodes/fd_manager.cc.s

SourceCodes/fiber.o: SourceCodes/fiber.cc.o

.PHONY : SourceCodes/fiber.o

# target to build an object file
SourceCodes/fiber.cc.o:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/SourceCodes/fiber.cc.o
.PHONY : SourceCodes/fiber.cc.o

SourceCodes/fiber.i: SourceCodes/fiber.cc.i

.PHONY : SourceCodes/fiber.i

# target to preprocess a source file
SourceCodes/fiber.cc.i:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/SourceCodes/fiber.cc.i
.PHONY : SourceCodes/fiber.cc.i

SourceCodes/fiber.s: SourceCodes/fiber.cc.s

.PHONY : SourceCodes/fiber.s

# target to generate assembly for a file
SourceCodes/fiber.cc.s:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/SourceCodes/fiber.cc.s
.PHONY : SourceCodes/fiber.cc.s

SourceCodes/hook.o: SourceCodes/hook.cc.o

.PHONY : SourceCodes/hook.o

# target to build an object file
SourceCodes/hook.cc.o:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/SourceCodes/hook.cc.o
.PHONY : SourceCodes/hook.cc.o

SourceCodes/hook.i: SourceCodes/hook.cc.i

.PHONY : SourceCodes/hook.i

# target to preprocess a source file
SourceCodes/hook.cc.i:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/SourceCodes/hook.cc.i
.PHONY : SourceCodes/hook.cc.i

SourceCodes/hook.s: SourceCodes/hook.cc.s

.PHONY : SourceCodes/hook.s

# target to generate assembly for a file
SourceCodes/hook.cc.s:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/SourceCodes/hook.cc.s
.PHONY : SourceCodes/hook.cc.s

SourceCodes/iomanager.o: SourceCodes/iomanager.cc.o

.PHONY : SourceCodes/iomanager.o

# target to build an object file
SourceCodes/iomanager.cc.o:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/SourceCodes/iomanager.cc.o
.PHONY : SourceCodes/iomanager.cc.o

SourceCodes/iomanager.i: SourceCodes/iomanager.cc.i

.PHONY : SourceCodes/iomanager.i

# target to preprocess a source file
SourceCodes/iomanager.cc.i:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/SourceCodes/iomanager.cc.i
.PHONY : SourceCodes/iomanager.cc.i

SourceCodes/iomanager.s: SourceCodes/iomanager.cc.s

.PHONY : SourceCodes/iomanager.s

# target to generate assembly for a file
SourceCodes/iomanager.cc.s:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/SourceCodes/iomanager.cc.s
.PHONY : SourceCodes/iomanager.cc.s

SourceCodes/scheduler.o: SourceCodes/scheduler.cc.o

.PHONY : SourceCodes/scheduler.o

# target to build an object file
SourceCodes/scheduler.cc.o:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/SourceCodes/scheduler.cc.o
.PHONY : SourceCodes/scheduler.cc.o

SourceCodes/scheduler.i: SourceCodes/scheduler.cc.i

.PHONY : SourceCodes/scheduler.i

# target to preprocess a source file
SourceCodes/scheduler.cc.i:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/SourceCodes/scheduler.cc.i
.PHONY : SourceCodes/scheduler.cc.i

SourceCodes/scheduler.s: SourceCodes/scheduler.cc.s

.PHONY : SourceCodes/scheduler.s

# target to generate assembly for a file
SourceCodes/scheduler.cc.s:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/SourceCodes/scheduler.cc.s
.PHONY : SourceCodes/scheduler.cc.s

SourceCodes/thread.o: SourceCodes/thread.cc.o

.PHONY : SourceCodes/thread.o

# target to build an object file
SourceCodes/thread.cc.o:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/SourceCodes/thread.cc.o
.PHONY : SourceCodes/thread.cc.o

SourceCodes/thread.i: SourceCodes/thread.cc.i

.PHONY : SourceCodes/thread.i

# target to preprocess a source file
SourceCodes/thread.cc.i:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/SourceCodes/thread.cc.i
.PHONY : SourceCodes/thread.cc.i

SourceCodes/thread.s: SourceCodes/thread.cc.s

.PHONY : SourceCodes/thread.s

# target to generate assembly for a file
SourceCodes/thread.cc.s:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/SourceCodes/thread.cc.s
.PHONY : SourceCodes/thread.cc.s

SourceCodes/timer.o: SourceCodes/timer.cc.o

.PHONY : SourceCodes/timer.o

# target to build an object file
SourceCodes/timer.cc.o:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/SourceCodes/timer.cc.o
.PHONY : SourceCodes/timer.cc.o

SourceCodes/timer.i: SourceCodes/timer.cc.i

.PHONY : SourceCodes/timer.i

# target to preprocess a source file
SourceCodes/timer.cc.i:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/SourceCodes/timer.cc.i
.PHONY : SourceCodes/timer.cc.i

SourceCodes/timer.s: SourceCodes/timer.cc.s

.PHONY : SourceCodes/timer.s

# target to generate assembly for a file
SourceCodes/timer.cc.s:
	$(MAKE) -f CMakeFiles/myitem.dir/build.make CMakeFiles/myitem.dir/SourceCodes/timer.cc.s
.PHONY : SourceCodes/timer.cc.s

test/hook_test.o: test/hook_test.cc.o

.PHONY : test/hook_test.o

# target to build an object file
test/hook_test.cc.o:
	$(MAKE) -f CMakeFiles/hook_test.dir/build.make CMakeFiles/hook_test.dir/test/hook_test.cc.o
.PHONY : test/hook_test.cc.o

test/hook_test.i: test/hook_test.cc.i

.PHONY : test/hook_test.i

# target to preprocess a source file
test/hook_test.cc.i:
	$(MAKE) -f CMakeFiles/hook_test.dir/build.make CMakeFiles/hook_test.dir/test/hook_test.cc.i
.PHONY : test/hook_test.cc.i

test/hook_test.s: test/hook_test.cc.s

.PHONY : test/hook_test.s

# target to generate assembly for a file
test/hook_test.cc.s:
	$(MAKE) -f CMakeFiles/hook_test.dir/build.make CMakeFiles/hook_test.dir/test/hook_test.cc.s
.PHONY : test/hook_test.cc.s

test/mytest.o: test/mytest.cc.o

.PHONY : test/mytest.o

# target to build an object file
test/mytest.cc.o:
	$(MAKE) -f CMakeFiles/mytest.dir/build.make CMakeFiles/mytest.dir/test/mytest.cc.o
.PHONY : test/mytest.cc.o

test/mytest.i: test/mytest.cc.i

.PHONY : test/mytest.i

# target to preprocess a source file
test/mytest.cc.i:
	$(MAKE) -f CMakeFiles/mytest.dir/build.make CMakeFiles/mytest.dir/test/mytest.cc.i
.PHONY : test/mytest.cc.i

test/mytest.s: test/mytest.cc.s

.PHONY : test/mytest.s

# target to generate assembly for a file
test/mytest.cc.s:
	$(MAKE) -f CMakeFiles/mytest.dir/build.make CMakeFiles/mytest.dir/test/mytest.cc.s
.PHONY : test/mytest.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... hook_test"
	@echo "... myitem"
	@echo "... mytest"
	@echo "... SourceCodes/fd_manager.o"
	@echo "... SourceCodes/fd_manager.i"
	@echo "... SourceCodes/fd_manager.s"
	@echo "... SourceCodes/fiber.o"
	@echo "... SourceCodes/fiber.i"
	@echo "... SourceCodes/fiber.s"
	@echo "... SourceCodes/hook.o"
	@echo "... SourceCodes/hook.i"
	@echo "... SourceCodes/hook.s"
	@echo "... SourceCodes/iomanager.o"
	@echo "... SourceCodes/iomanager.i"
	@echo "... SourceCodes/iomanager.s"
	@echo "... SourceCodes/scheduler.o"
	@echo "... SourceCodes/scheduler.i"
	@echo "... SourceCodes/scheduler.s"
	@echo "... SourceCodes/thread.o"
	@echo "... SourceCodes/thread.i"
	@echo "... SourceCodes/thread.s"
	@echo "... SourceCodes/timer.o"
	@echo "... SourceCodes/timer.i"
	@echo "... SourceCodes/timer.s"
	@echo "... test/hook_test.o"
	@echo "... test/hook_test.i"
	@echo "... test/hook_test.s"
	@echo "... test/mytest.o"
	@echo "... test/mytest.i"
	@echo "... test/mytest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

